### ISSUE TITLE
Redux store setup

### ISSUE THREAD

**Issue by johnhaup** [aaranda82/my-recipes#6]
- [x] Create a `reducers` folder and move your root reducer to it
- [x] Create a `store.ts` file
~~Use redux's `createStore` method to create a new store.  Pass this store your `rootReducer`.  Export the `store`.~~ 
~~Import your `store` into `App.tsx`.~~
~~Using `react-redux`'s `Provider` component, wrap your app in the `Provider` and pass the provider the imported `store`.~~
~~For the commit message for this issue, reference the issue number, for example: "Wrap app in redux provider.  #6"~~

**What's happening here?**
Redux is powerful in that it provides a **global** state.  It does this by taking your reducers and providing them to all the children of the Provider component.

**Comment by johnhaup** [comment]
Looks like most of this is done, with the Provider in the index.tsx file.  I don't think this is a problem.  It's just one level higher in the tree.  I'm not seeing the Count or Auth components visible on the live page though.  Should they be?

**Comment by aaranda82** [comment]
I was still using .env for API key, should work now.

**Comment by johnhaup** [comment]
Provider logic is in entry file vs App component so doesn't need to be recreated.
